- name: Setup Android SDK
  uses: android-actions/setup-android@v4
  with:
    packages: ''
    accept-android-sdk-licenses: true
    log-accepted-android-sdk-licenses: false

- name: Install required Android SDK packages
  run: |
    sdkmanager "platform-tools"
    sdkmanager "platforms;android-34"
    sdkmanager "build-tools;34.0.0"
